### Recuperar todas las películas
GET http://localhost:1324/movies

### Recuperar una película por
GET http://localhost:1324/movies/2a4b33fe-7aea-11f0-8f15-346f24a41b94

###Recuperar todas las películas por un género
GET http://localhost:1324/movies?genre=ACTION

### Crear una pelicua
POST http://localhost:1324/movies
Content-Type: application/json

{ 
    "title": "SOFIA8",
    "year": 2000,
    "director": "Ridley Scott",
    "duration": 155,
    "poster": "https://img.fruugo.com/product/0/60/14417600_max.jpg",
    "genre": [
      "Action",
      "Adventure"
    ]
}

### Eliminar una pelicua
DELETE  http://localhost:1324/movies/8fb17ae1-bdfe-45e5-a871-4772d7e526b8

### actualizar una película (parcialmente)
PATCH  http://localhost:1324/movies/8fb17ae1-bdfe-45e5-a871-4772d7e526b8
Content-Type: application/json

{ 
  "title": "nada",
  "year": 2004
}

